In [3]:
#load numpy library
import numpy as np

In [4]:
#Creat a function name p for the print function
def p(v):
    print(v)

In [5]:
# Create an np Array with a data type of an integer and size of 16 bits
a = np.array([1,2,3], dtype = "int16")
p(a)
type(a)

[1 2 3]


numpy.ndarray

In [6]:
# Create a numpy array of 2 dimentions
b = np.array([[1,2,3],[2,3,100]])
p(b)
# .ndim returns the # of dimentions
p(b.ndim)
# .dtype returns the data type of the array or martix
p(b.dtype)

[[  1   2   3]
 [  2   3 100]]
2
int32


In [7]:
# .ndim returns the # of dimentions
a.ndim

1

In [8]:
# .ndim returns the # of dimentions
b.ndim

2

In [9]:
# .shape returns the shape of the matric (rows, columns) as a tuple
p(a.shape)
type(a.shape)

(3,)


tuple

In [10]:
# .dtype returns the data type of the array or martix
a.dtype

dtype('int16')

In [11]:
# .itemsize Length of one array element in bytes.
p(a.itemsize)
p(a)

2
[1 2 3]


In [12]:
# Look for a specific row & specific column [row,column] index starts at 0, : means all rows or all column
p(b)


[[  1   2   3]
 [  2   3 100]]


In [13]:
# first row, all columns
p(b[0, :])

[1 2 3]


In [25]:
# second row, all columns
p(b[1, :])

[  2   3 100]


In [26]:
# first row, 3rd column
p(b[0, 2])

3


In [27]:
p(b)

[[  1   2   3]
 [  2   3 100]]


In [24]:
# insert 10 into the first row & first column item place
b[0,0] = 10
b

array([[ 10,   2,   3],
       [  2,   3, 100]])

In [28]:
# insert 1000 into all the rows of the 3rd column
b[:,2] = 1000
p(b)

[[   1    2 1000]
 [   2    3 1000]]


In [32]:
# array of 3 dimentions
bb = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
p(bb)
p(bb.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [33]:
#first section, second row, all columns
bb[0,1,:]

array([3, 4])

In [35]:
# all sections, second row, all columns
bb[:,1,:]

array([[3, 4],
       [7, 8]])

In [35]:
# create an all zero matrix of 10 row and 3 columns
Zeros = np.zeros((10,3))
p(Zeros)
p(Zeros.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(10, 3)


In [17]:
# Create an equally spaced numpy.array of 6 elements
p("Create an equally spaced numpy.array of 6 elements")
x = np.arange(6, dtype=int)
p(x)
p(type(x))

p("x.shape:")
p(x.shape)

# Create a range object of 6 elemetns
p("Create a range object of 6 elemetns:")
y = range(6)
p(y)
p(type(y))
p(len(y))

# use the np.full_like(array or matrix, value to be inserted in all elemetns)
p("Wse the np.full_like(array or matrix, value to be inserted in all elemetns):")
gg = np.full_like(x, 1)
p(x)
p(gg)

# np.arange?
# np.full_like(x, 0.1)
# array([0, 0, 0, 0, 0, 0])
# np.full_like(x, 0.1, dtype=np.double)
# array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
# np.full_like(x, np.nan, dtype=np.double)
# array([nan, nan, nan, nan, nan, nan]) 

Create an equally spaced numpy.array of 6 elements
[0 1 2 3 4 5]
<class 'numpy.ndarray'>
x.shape:
(6,)
Create a range object of 6 elemetns:
range(0, 6)
<class 'range'>
6
Wse the np.full_like(array or matrix, value to be inserted in all elemetns):
[0 1 2 3 4 5]
[1 1 1 1 1 1]


In [34]:
# Create a 4x2 matrix of all random values between 0 to 1
x = np.random.rand(4,5)
p(x)
p(x.shape)

[[0.415569   0.88638329 0.01941229 0.8715382  0.57474772]
 [0.94351808 0.34681795 0.80369158 0.26491282 0.90749575]
 [0.69249646 0.47211067 0.63325251 0.56821703 0.65407706]
 [0.01987187 0.19386217 0.46147306 0.8625155  0.14917718]]
(4, 5)


In [63]:
# Create a 4x2 matrix of all random values between 0 to 5
zaz = 5 * np.random.rand(5,5)
p(zaz)
p(zaz.shape)

[[1.73301603e+00 6.28336566e-01 4.81292562e+00 4.79855434e+00
  3.97693930e+00]
 [4.27525944e+00 1.73203729e-03 4.27870498e+00 4.02804180e+00
  2.76773371e+00]
 [4.96084844e+00 2.50680334e+00 2.37299882e+00 5.66895197e-01
  3.31839389e+00]
 [4.85025700e+00 1.21243441e+00 8.43060082e-02 1.68515904e+00
  4.13167326e+00]
 [4.05836909e+00 4.60329075e+00 1.62017378e+00 1.91233962e+00
  4.67724697e+00]]
(5, 5)


In [44]:
# Create a 5x2 matrix with random integer values between 0 to 10
p("5x2 matrix with random integer values between 0 to 10:")
a = np.random.randint(10, size=(5,2))
print(a)
p(a.shape)
p("----------------------------------------------------------------------")

# Create a 2nd 2x5 matrix with random integer values between 0 to 10
p("Create a 2nd 2x5 matrix with random integer values between 0 to 10")
b = np.random.randint(10, size=(2,5))
print(b)
p("----------------------------------------------------------------------")

# Multiply matrix x & b using the matmul function 
p("z=np.matmul(a,b):")
z=np.matmul(a,b)
print(z)
p(z.shape)
p("----------------------------------------------------------------------")

# Multiply matrix x & b using the matmul function 
p("a@b:")
z=a@b
print(z)
p(z.shape)
p("----------------------------------------------------------------------")

# Find the determenate of the matrix
p("Find the determenate of the matrix")
p("np.linalg.det(z):")
zoz = np.linalg.det(z)
print(zoz)

5x2 matrix with random integer values between 0 to 10:
[[2 3]
 [6 3]
 [0 3]
 [0 1]
 [5 2]]
(5, 2)
----------------------------------------------------------------------
Create a 2nd 2x5 matrix with random integer values between 0 to 10
[[5 9 5 0 2]
 [3 8 2 4 1]]
----------------------------------------------------------------------
z=np.matmul(a,b):
[[19 42 16 12  7]
 [39 78 36 12 15]
 [ 9 24  6 12  3]
 [ 3  8  2  4  1]
 [31 61 29  8 12]]
(5, 5)
----------------------------------------------------------------------
a@b:
[[19 42 16 12  7]
 [39 78 36 12 15]
 [ 9 24  6 12  3]
 [ 3  8  2  4  1]
 [31 61 29  8 12]]
(5, 5)
----------------------------------------------------------------------
Find the determenate of the matrix
np.linalg.det(z):
1.5994508252957338e-44


In [30]:
# creat a random array of 5 int
b = np.random.randint(10, size=(5,))
print(b)
p(b.ndim)

[7 9 0 8 6]
1


In [90]:
# Create a matrix of size 2x2
a = np.array([[1,2],[2,3]])
p("Matrix a:")
p(a)
p(a.shape)

b = np.array([[8,4],[4,7]])
p("Matrix b:")
p(b)

p("Use np.dot(a,b):")
print(np.dot(a,b))
p("Use a@b:")
print(a@b)
p("Use matmul function:")
p(np.matmul(a,b))
p("Use the a * b")
p(a * b)

Matrix a:
[[1 2]
 [2 3]]
(2, 2)
Matrix b:
[[8 4]
 [4 7]]
Use np.dot(a,b):
[[16 18]
 [28 29]]
Use a@b:
[[16 18]
 [28 29]]
Use matmul function:
[[16 18]
 [28 29]]
Use the a * b
[[ 8  8]
 [ 8 21]]


In [103]:
# Create a matrix of 2x2
a = np.array(([1,2],[3,4]))
p(a)

[[1 2]
 [3 4]]


In [107]:
# Create a matrix of size 2v2 filled with random int values from 0 to 10
b = np.random.randint(10, size=[2,2])
p(b)

# Get the determinant of b
p(np.linalg.det(b))

[[0 1]
 [1 9]]
-1.0


In [111]:
# Create an identity matrix of size 5x5
x = np.identity(5)
print(x)

# Get the determinant of the matrix
y = np.linalg.det(x)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
1.0


In [124]:
# Create a 2x3 matrix
stats = np.array([[52,40,41],[60,520,11]])
print(stats)
p(stats.ndim)

[[ 52  40  41]
 [ 60 520  11]]
2


In [129]:
# Find the maximum row wise
p("maximum row wise:")
p(np.max(stats, axis=1))

# Find the maximum coumn wise
p("maximum coumn wise:")
p(np.max(stats, axis=0))

maximum row wise:
[ 52 520]
maximum coumn wise:
[ 60 520  41]


In [148]:
# get the sum row wise
p("Sum row wise:")
z=np.sum(stats, axis=1)
p(z)
p(z.shape)
p(type(z))
p(z[1])

p("-------------------------------------------")
zz = z.reshape(1,2)
p(zz)
p(zz.shape)
p(type(zz))
p(zz[0,1])
p("-------------------------------------------")

# get the sum column wise
p("Sum column wise:")
p(np.sum(stats, axis=0))

Sum row wise:
[133 591]
(2,)
<class 'numpy.ndarray'>
591
-------------------------------------------
[[133 591]]
(1, 2)
<class 'numpy.ndarray'>
591
-------------------------------------------
Sum column wise:
[112 560  52]


In [151]:
# Create a matrix of 2 x 4
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
p("-------------------------------------------")

# reshape the matrix from 2x4 to 4x2
after = before.reshape(4,2)
p(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
-------------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [152]:
# sum array1 + array2
x=np.array([1,2,3])+np.array([4,5,6])
p(x)


[5 7 9]


In [160]:
# Create an array of 21 equally spaced between -10 to 10
my_array = np.linspace(-10,10,21)
print(my_array)
# Max value of numpy array
x=my_array.max()
p(x)

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.  10.]
10.0


In [165]:
# Create an array of 21 equally spaced between -10 to 10
my_array = np.linspace(-10,10,21)
print(my_array)

# Argmax value of numpy array (location at which the max occurs)
x=my_array.argmax()
p(x)

[-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.   0.   1.   2.   3.
   4.   5.   6.   7.   8.   9.  10.]
20


In [173]:
# create array1
v1=np.array([1,2,3])
# create array2
v2=np.array([4,5,6])

# vertically stack v1 and v2
v3 = np.vstack((v1,v2))
p(v3)

# find the exponent of v3
z = np.exp(v3)
p(z)

[[1 2 3]
 [4 5 6]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [184]:
# create 2 arrays of 3 elements
my_array1 = np.array([1,2,3])
my_array2 = np.array([4,5,6])


# print array1 and array2
p("array1 & array2:")

print(my_array1,my_array2)
p("-------------------------------------------")

# stack array1 and array 2 horizontilly
p("Horizontal stack:")
print(np.hstack((my_array1,my_array2)))

p("-------------------------------------------")

# stoack array1 and array2 vertically
p("vertical stack:")
p(np.vstack((my_array1, my_array2)))
np.vstack?

array1 & array2:
[1 2 3] [4 5 6]
-------------------------------------------
Horizontal stack:
[1 2 3 4 5 6]
-------------------------------------------
vertical stack:
[[1 2 3]
 [4 5 6]]


In [198]:
# Create array a
a = np.array([[1], [2], [3]])
p("Print a:")
p(a)

# Create array b
b = np.array([[4], [5], [6]])
p("Print b:")
p(b)

# vertically stack a & b
p("Vstack a & b")
p(np.vstack((a,b)))

# Horizontally stack a & b
p("Hstack a & b")
p(np.hstack((a,b)))

Print a:
[[1]
 [2]
 [3]]
Print b:
[[4]
 [5]
 [6]]
Vstack a & b
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Hstack a & b
[[1 4]
 [2 5]
 [3 6]]


In [226]:
# Create an array of 10 elements divided equally between 0 to 10
p("Print Array")
my_array = np.linspace(0,9,10)
p(my_array)

# Insert 100 into the first element
my_array[0] = 100
p("Insert 100 into the first element")
p(my_array)
#print(my_array)
#my_array = my_array.sort()
#my_array

# Sorting your array
z = np.sort(my_array)
p("Sort array")
p(z)
p("-------------------------------------------")

# Reverse sorting array
p("Sorting Descending")
zz = -np.sort(-z)
p(zz)

Print Array
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Insert 100 into the first element
[100.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
Sort array
[  1.   2.   3.   4.   5.   6.   7.   8.   9. 100.]
-------------------------------------------
Sorting Descending
[100.   9.   8.   7.   6.   5.   4.   3.   2.   1.]


In [250]:
# Create array1 with 12 elements equally spaced between  0 to 11
array1 = np.linspace(0,11,12)
p("Array1")
p(array1)

# Reshape array1 into a 2x6 matrix
p("matrix1")
matrix1 = array1.reshape(2,6)
p(matrix1)


# Create array2 with 12 elements equally spaced between  0 to 100
array2 = np.linspace(0,100,12)
p("Array2")
p(array2)

# Reshape array2 into a 2x6 matrix
p("matrix2")
matrix2 = array2.reshape(2,6)
p(matrix2)

# Multiply matrix1 with matrix2 using linear algebra matrix multiplication
z=my_matrix1 @ my_matrix2
p("matrix1 @ matrix2")

p(z)

Array1
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
matrix1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
Array2
[  0.           9.09090909  18.18181818  27.27272727  36.36363636
  45.45454545  54.54545455  63.63636364  72.72727273  81.81818182
  90.90909091 100.        ]
matrix2
[[  0.           9.09090909  18.18181818  27.27272727  36.36363636
   45.45454545]
 [ 54.54545455  63.63636364  72.72727273  81.81818182  90.90909091
  100.        ]]
matrix1 @ matrix2
[[ 909.09090909 1033.05785124]
 [2396.69421488 2818.18181818]]


In [168]:
zz = np.matmul(my_matrix1,my_matrix2)
p(zz)

[[ 909.09090909 1033.05785124]
 [2396.69421488 2818.18181818]]


In [279]:
# Generating random numbers using Numpy's random function
# The function np.random.rand will take length of an array or the shape of the 
np.random.rand?


In [282]:
# Creates an array of 4 elements of random numbers from [0,1) - uniform distribution
random_array = np.random.rand(4)
p(random_array)
p(random_array.shape)

[0.24082878 0.10029394 0.01642963 0.92952932]
(4,)


In [283]:
# Generating a random 5x5 matrix (Uniform distribution)
random_matrix = np.random.rand(5,5)
p(random_matrix)
p(random_matrix.shape)

[[0.66991655 0.78515291 0.28173011 0.58641017 0.06395527]
 [0.4856276  0.97749514 0.87650525 0.33815895 0.96157015]
 [0.23170163 0.94931882 0.9413777  0.79920259 0.63044794]
 [0.87428797 0.29302028 0.84894356 0.61787669 0.01323686]
 [0.34723352 0.14814086 0.98182939 0.47837031 0.49739137]]
(5, 5)


In [315]:
# np.random.randint(lowst value, highest value, array or matrix size(as a tuple))
z=np.random.randint(low=-10,high=10, size=(10))
p(z)
np.random.randint?

[ -5   4   7  -1   4   2  -8  -7 -10   2]


In [295]:
# create an array of 100 random integers with a minimum value of 10, maximum value of 10
z=np.random.randint(low=-10,high=10,size=(10,10))
p("Print 10x10 random int matrix, low: -10, high: 10")
p(z)
p(z.shape)
p("-------------------------------------------")

# Sort the array
zsort = np.sort(z)
p("Print sorted matrix")
p(zsort)
p("-------------------------------------------")

# Reshape the matrix into array
p("Print reshaped matrix into a single 100 element array")

zz = z.reshape(100)
p(zz)
p(zz.shape)



Print 10x10 random int matrix, low: -10, high: 10
[[  2  -4   0   0  -5   0  -2   5  -6   9]
 [ -5  -7  -3   5   5   0   9   3  -3  -5]
 [ -3   8  -3 -10   2  -3  -2   5  -6   0]
 [  6  -2   6   4 -10   5   2   9  -8   3]
 [ -8   7   3   6  -5  -3  -9   7  -8  -9]
 [ -6  -2   8  -9  -7   6  -7  -5  -9  -7]
 [ -3  -9  -9  -3  -6   3   2   8 -10   1]
 [  9  -8   3  -6   6   6   0   1  -7  -2]
 [  9   4 -10 -10  -8   1  -5  -8  -3   2]
 [  1   9  -9   6   8   8   4   5   5  -5]]
(10, 10)
-------------------------------------------
Print sorted matrix
[[ -6  -5  -4  -2   0   0   0   2   5   9]
 [ -7  -5  -5  -3  -3   0   3   5   5   9]
 [-10  -6  -3  -3  -3  -2   0   2   5   8]
 [-10  -8  -2   2   3   4   5   6   6   9]
 [ -9  -9  -8  -8  -5  -3   3   6   7   7]
 [ -9  -9  -7  -7  -7  -6  -5  -2   6   8]
 [-10  -9  -9  -6  -3  -3   1   2   3   8]
 [ -8  -7  -6  -2   0   1   3   6   6   9]
 [-10 -10  -8  -8  -5  -3   1   2   4   9]
 [ -9  -5   1   4   5   5   6   8   8   9]]
---------------

In [46]:
# np.random.seed(number) will set a seeding to make the random values constant random value for all python users
np.random.seed(0)
x = np.random.randint(1,7, size=2)
p(x)

[5 6]


In [189]:
# Setting seed (very important - for future projects to ensure reproducible results)
np.random.seed(123)
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

In [190]:
np.random.seed(123)
np.random.rand(5)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

In [317]:
# np.linspace(starting value, end value, number of elements in this array)
y = np.linspace(0,10, 101)
p(y)
p(len(y))
p(type(y))

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]
101
<class 'numpy.ndarray'>


In [205]:
# The essential difference between NumPy linspace and NumPy arange 
# is that linspace enables you to control the precise end value, 
# whereas arange gives you more direct control over the increments between values in the sequence.
y = np.arange(0,10, 0.2)
p(y)
p(len(y))
type(y)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
50


numpy.ndarray

In [45]:
# create an array of 10 random elements
y = np.random.rand(2,5)
p(y)
p(len(y))

# calculate the mean of this matrix
p("The mean of the entire matrix: ")
p(np.mean(y))

# calculate the mean of this matrix column wise
p("The mean column wise: ")
p(np.mean(y, axis= 0))

# calculate the mean of this matrix column row
p("The mean row wise: ")
p(np.mean(y, axis= 1))

# calculate the median of this matrix
p("median: ")
p(np.median(y))

# calculate the median of this matrix row wise
p("median row wise: ")
p(np.median(y, axis = 1))

# calculate the variance of this matrix
p("variance: ")
p(np.var(y))

# calculate the variance of this matrix row wise
p("variance row wise: ")
p(np.var(y, axis = 1))

[[0.61073732 0.64775064 0.57817151 0.59620984 0.18240835]
 [0.51169856 0.58312493 0.43621324 0.4000174  0.53713181]]
2
The mean of the entire matrix: 
0.5083463584595181
The mean column wise: 
[0.56121794 0.61543778 0.50719237 0.49811362 0.35977008]
The mean row wise: 
[0.52305553 0.49363719]
median: 
0.5576516586744904
median row wise: 
[0.59620984 0.51169856]
variance: 
0.0172118615159497
variance row wise: 
[0.02953336 0.00445765]


In [363]:
# Reshape y into a 6 element array
zz = y.reshape(1,6)
p(zz)
p(zz.shape)
p(zz.ndim)
p(len(zz))
p(np.mean(zz, axis=0))


[[0.92984809 0.71252314 0.8120745  0.45476144 0.32726268 0.13830675]]
(1, 6)
2
1
[0.92984809 0.71252314 0.8120745  0.45476144 0.32726268 0.13830675]


In [48]:
# create an array with 50 random values
a = np.random.rand(50)
p(a)
p(len(a))

# create a subset of the above array with with first 25 values
b = a[0:25]
p(b)
p(len(b))

# create a second subset of the above array with the last 25 values
z = a[25:50]
p(z)
p(len(z))

[0.63427406 0.95894927 0.65279032 0.63505887 0.99529957 0.58185033
 0.41436859 0.4746975  0.6235101  0.33800761 0.67475232 0.31720174
 0.77834548 0.94957105 0.66252687 0.01357164 0.6228461  0.67365963
 0.971945   0.87819347 0.50962438 0.05571469 0.45115921 0.01998767
 0.44171092 0.97958673 0.35944446 0.48089353 0.68866118 0.88047589
 0.91823547 0.21682214 0.56518887 0.86510256 0.50896896 0.91672295
 0.92115761 0.08311249 0.27771856 0.0093567  0.84234208 0.64717414
 0.84138612 0.26473016 0.39782075 0.55282148 0.16494046 0.36980809
 0.14644176 0.56961841]
50
[0.63427406 0.95894927 0.65279032 0.63505887 0.99529957 0.58185033
 0.41436859 0.4746975  0.6235101  0.33800761 0.67475232 0.31720174
 0.77834548 0.94957105 0.66252687 0.01357164 0.6228461  0.67365963
 0.971945   0.87819347 0.50962438 0.05571469 0.45115921 0.01998767
 0.44171092]
25
[0.97958673 0.35944446 0.48089353 0.68866118 0.88047589 0.91823547
 0.21682214 0.56518887 0.86510256 0.50896896 0.91672295 0.92115761
 0.08311249 0.27771

In [50]:
# reshape the first subset into 5x5 matrix
bb = b.reshape(5,5)
p(bb.shape)

# reshape the second subset into a 5x5 matrix
zz = z.reshape(5,5)
p(zz.shape)

# multiply the 2 matrices using matrix operation
gg = np.matmul(bb,zz)
p(gg)
p(gg.shape)
gg_det = np.linalg.det(gg)
p(gg_det)

# we can also use the @ operator to perform the matrix multiplciatoin 
hh = bb @ zz
p(hh)

(5, 5)
(5, 5)
[[3.18545534 1.61238935 1.80366033 1.76155404 1.87222695]
 [2.09769356 1.19552912 1.20306856 1.10556173 1.16822816]
 [2.83189422 1.75210653 1.61241685 1.30365046 1.51797831]
 [2.50696761 1.53433907 1.55708581 1.12116715 1.22215712]
 [1.22499223 0.69664209 0.49422697 0.594429   0.74084857]]
(5, 5)
-0.001038619032569381
[[3.18545534 1.61238935 1.80366033 1.76155404 1.87222695]
 [2.09769356 1.19552912 1.20306856 1.10556173 1.16822816]
 [2.83189422 1.75210653 1.61241685 1.30365046 1.51797831]
 [2.50696761 1.53433907 1.55708581 1.12116715 1.22215712]
 [1.22499223 0.69664209 0.49422697 0.594429   0.74084857]]
